<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<title>Studywithcomp - Learn and Grow with Us</title>';
echo '<style>';
echo '/* Global styles */';
echo '';
echo 'body {';
echo 'font-family: Arial, sans-serif;';
echo 'margin: 0;';
echo 'padding: 0;';
echo '}';
echo '';
echo 'header {';
echo 'background-color: #333;';
echo 'color: #fff;';
echo 'display: flex;';
echo 'flex-direction: column;';
echo 'align-items: center;';
echo 'padding: 10px;';
echo '}';
echo '';
echo 'nav ul {';
echo 'list-style-type: none;';
echo 'margin: 0;';
echo 'padding: 0;';
echo 'display: flex;';
echo '}';
echo '';
echo 'nav li {';
echo 'margin: 0 10px;';
echo '}';
echo '';
echo 'nav a {';
echo 'color: #fff;';
echo 'text-decoration: none;';
echo '}';
echo '';
echo 'nav a:hover {';
echo 'text-decoration: underline;';
echo '}';
echo '';
echo 'main {';
echo 'max-width: 800px;';
echo 'margin: 20px auto;';
echo 'padding: 0 20px;';
echo '}';
echo '';
echo 'footer {';
echo 'background-color: #333;';
echo 'color: #fff;';
echo 'text-align: center;';
echo 'padding: 10px;';
echo '}';
echo '';
echo '/* Specific page styles */';
echo '';
echo 'h1 {';
echo 'font-size: 36px;';
echo 'align-items: center;';
echo 'margin: 0;';
echo '}';
echo '';
echo 'h2 {';
echo 'font-size: 24px;';
echo 'align-items: center;';
echo 'margin: 30px 0 20px 0;';
echo '}';
echo '';
echo 'h3 {';
echo 'font-size: 20px;';
echo 'margin: 20px 0 10px 0;';
echo '}';
echo '';
echo 'p {';
echo 'line-height: 1.5;';
echo '}';
echo '';
echo 'a {';
echo 'display: inline-block;';
echo 'background-color: #333;';
echo 'color: #fff;';
echo 'padding: 10px 20px;';
echo 'margin: 20px 0;';
echo 'border-radius: 5px;';
echo 'text-decoration: none;';
echo 'transition: background-color 0.3s ease;';
echo '}';
echo '';
echo 'a:hover {';
echo 'background-color: #666;';
echo '}';
echo '';
echo 'ul {';
echo 'padding: 0;';
echo '}';
echo '';
echo 'li {';
echo 'margin-bottom: 40px;';
echo 'display: flex;';
echo 'flex-direction: column;';
echo 'align-items: center;';
echo 'text-align: center;';
echo '}';
echo '';
echo 'li img {';
echo 'max-width: 100%;';
echo '}';
echo '';
echo '@media only screen and (max-width: 600px) {';
echo 'nav {';
echo 'flex-direction: column;';
echo '}';
echo '';
echo 'nav li {';
echo 'margin: 10px 0;';
echo '}';
echo '';
echo 'h1 {';
echo 'font-size: 24px;';
echo '}';
echo '';
echo 'h2 {';
echo 'font-size: 20px;';
echo 'margin: 20px 0;';
echo '}';
echo '';
echo 'h3 {';
echo 'font-size: 18px;';
echo 'margin: 10px 0;';
echo '}';
echo '';
echo 'p {';
echo 'font-size: 16px;';
echo 'line-height: 1.2;';
echo '}';
echo '}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '<header>';
echo '<h1>Studywithcomp</h1>';
echo '<nav>';
echo '<ul>';
echo '<li><a href="https://studywithcomp.github.io/Home/">Home</a></li>';
echo '<li><a href="https://studywithcomp.github.io/Home/courses.html">Courses</a></li>';
echo '<li><a href="https://studywithcomp.github.io/Home/internships.php">Internships</a></li>';
echo '<li><a href="https://studywithcomp.github.io/Home/contact.html">Contact Us</a></li>';
echo '</ul>';
echo '</nav>';
echo '</header>';
echo '<main>';
echo '';
echo '<h2>Featured Internships Platforms</h2>';
echo '<ul>';
echo '<li>';
echo '<img src="assets/images/I1.png" alt="Internship 1">';
echo '<h3>Future Ready Talent Internship Program - 2023</h3>';
echo '<p>Future Ready Talent Program is a free virtual student internship program that upskills students to enhance their employability. Students can earn numerous learning benefits, in accordance with an AICTE approved curriculum. Upon successful completion of the internship, students will receive a certificate from Microsoft and NASSCOM, and will be eligible to access career drives and mentorship opportunities.</p>';
echo '<a href="https://futurereadytalent.in/">Apply Now</a>';
echo '</li>';
echo '<li>';
echo '<img src="assets/images/I2.jpeg" alt="Internship 2">';
echo '<h3>Internshala Internship</h3>';
echo '<p>Internshala is an online platform that provides internships to students and fresh graduates. It offers a wide range of internships across various domains such as engineering, management, media, law, design, and more. Internshala partners with various companies across India and provides students with opportunities to gain practical experience and enhance their skills. These internships can range from a few weeks to several months and can be part-time or full-time.</p>';
echo '<a href="https://internshala.com/i/FRC34-ISP34STUD7066">Apply Now</a>';
echo '</li>';
echo '<li>';
echo '<img src="assets/images/I3.jpg" alt="Internship 3">';
echo '<h3>Graphic Design Internship</h3>';
echo '<p>Join our design team and help us create beautiful visual assets for our marketing campaigns and products. You'll gain experience in Adobe Creative Suite, branding, and layout design.</p>';
echo '<a href="#">Apply Now</a>';
echo '</li>';
echo '</ul>';
echo '</main>';
echo '';
echo '<footer>';
echo '<!--<div class="social-media">';
echo '<!--<a href="#"><img src="facebook.png" alt="Facebook"></a>-->';
echo '<!--<a href="#"><img src="twitter.png" alt="Twitter"></a>-->';
echo '<!--<a href="#"><img src="instagram.png" alt="Instagram"></a>-->';
echo '<!--</div>-->';
echo '<div class="contact-info">';
echo '<h4>Contact Us</h4>';
echo '<!--<p><strong>Address:</strong> 123 Main Street, Anytown USA</p>-->';
echo '<!--"<p><strong>Phone:</strong> (555) 123-4567</p>"-->';
echo '<p><strong>Email:</strong> infostudywithcomp@gmail.com</p>';
echo '</div>';
echo '<p>&copy; 2023 Studywithcomp. All rights reserved.</p>';
echo '</footer>';
?>
